re-add cxx11-cxx23 check

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -34,7 +34,7 @@ jobs:
           
           # Use older ubuntu to maximise backward compatibility
           - {os: ubuntu-22.04,   r: 'devel', http-user-agent: 'release'}
-          - {os: ubuntu-22.04,   r: 'devel', http-user-agent: 'release', custom: 'no-legacy-nonapi'}
+          - {os: ubuntu-22.04,   r: 'devel', http-user-agent: 'release', custom: 'non-api'}
           - {os: ubuntu-22.04,   r: 'release', custom: 'no-cpp4rtest'}
           - {os: ubuntu-22.04,   r: 'oldrel-1'}
           - {os: ubuntu-22.04,   r: 'oldrel-2'}
@@ -72,9 +72,18 @@ jobs:
           needs: check
 
       - name: Set NO_LEGACY_NONAPI flag
-        if: matrix.config.custom == 'no-legacy-nonapi'
+        if: matrix.config.custom == 'non-api'
         run: |
           sed -i 's/PKG_CPPFLAGS = /PKG_CPPFLAGS = -DNO_LEGACY_NONAPI /' cpp4rtest/src/Makevars.in
+
+      - name: Check for non-API symbols
+        if: matrix.config.custom == 'non-api'
+        run: |
+          # Check for known non-API symbols that are being removed from R
+          if grep -rE 'R_NamespaceRegistry' inst/include/; then
+            echo "::error::Found non-API symbols in inst/include/"
+            exit 1
+          fi
 
       - name: Install cpp4rtest
         if: matrix.config.custom != 'no-cpp4rtest'
